/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@jamiekyu/website-header/**/*.{js,jsx,ts,tsx}",
  ],
  safelist: [
    'hidden',
    'flex',
    'md:hidden',
    'md:flex',
    'space-x-8',
    'translate-y-0',
    '-translate-y-full',
    'h-16',
    // Website header classes
    'fixed',
    'top-0',
    'left-0',
    'right-0',
    'z-50',
    'bg-white',
    'shadow-sm',
    'border-b',
    'border-gray-200',
    'transition-transform',
    'duration-300',
    'max-w-7xl',
    'mx-auto',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'justify-between',
    'items-center',
    'flex-shrink-0',
    'text-2xl',
    'font-bold',
    'text-gray-900',
    'hover:text-gray-700',
    'text-gray-700',
    'hover:text-gray-900',
    'px-3',
    'py-2',
    'text-sm',
    'font-medium',
    'transition-colors',
    'border-t',
    'pt-4',
    'pb-4',
    'flex-col',
    'space-y-2',
    'p-2',
    'h-6',
    'w-6',
    'pt-16',
    'py-2',
    'py-4',
    'py-6',
    'pb-4',
    'whitespace-nowrap'
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
